void playerDetails();
void initializePieces();
void initializePlayers();
void handleTurn(int rolledNumber);
int rollDice();
int whoStartGame();
void mystryCellGenerator();
void detailsOfEachRound();
int countPiecesOnBoard(int currentPlayer);
int ableToStartPiece(int currentPlayer);
void startPiece(int currentPlayer,int pieceIndex);
int ableToMove(int currentPlayer);
int Toss();
void adjustPosition(int currentPlayer,int pieceIndex);
void rotation(int currentPlayer, int pieceIndex, int toss);
void movePiece(int currentPlayer, int rolledNumber, int pieceIndex);
int ableToMoveInHomeStraight(int currentPlayer,int rolledNumber);
void MoveInHomeStraight(int currentPlayer,int rolledNumber,int pieceIndex);
void findWinner(int currentPlayer);
int ableToCapture(int currentPlayer,int rolledNumber);
void capturePlayer(int rolledNumber, int currentPlayer,int pieceIndex);
void handleBriefingRound(int currentPlayer);
void handleMysteryCell(int currentPlayer, int pieceIndex);
int teleportingPower(int currentPlayer,int pieceIndex,int rolledNumber);
void redPlayer(int rolledNumber);
void greenPlayer(int rolledNumber);
void yellowPlayer(int rolledNumber);
int ableToMoveToMystryCell(int currentPlayer,int rolledNumber);
void bluePlayer(int rolledNumber);
void Play();
